### ISSUE TITLE
Redis setup with dokku

### ISSUE THREAD

**Issue by etewiah** [Wafris/wafris-rb#68]
Good work on wafris - I heard about it on the Rails podcast and have added it to my todo list.

I use dokku for deployment and I provision my redis with that. It may turn out to be quite easy to set it up with wafris but I won't get a chance to try it out this week as I'm quite busy.

Just created this partly as a reminder to me to come back but also I think it would be good to add dokku setup to your docs.

**Comment by rmcastil** [comment]
@etewiah happy to add dokku to the docs. Have you been able to get the WAF going?

**Comment by etewiah** [comment]
@rmcastil  thanks for the reply.  I am now no longer managing infrastructure so will no longer need Wafris.  It was good to learn about it though and if I need a firewall in the future I will certainly come back to it.
