### ISSUE TITLE
Deprecation error when upgrading to Rails 7.2.0

### ISSUE THREAD

**Issue by seanwmitchell** [Wafris/wafris-rb#79]
When I run bin/dev after upgrading Rails from '7.1.3.4' to '7.2.0'

10:18:08 web.1     | started with pid 22332
10:18:08 css.1     | started with pid 22333
10:18:08 redis.1   | started with pid 22334
10:18:08 sidekiq.1 | started with pid 22335
10:18:08 redis.1   | 22334:C 18 Aug 2024 10:18:08.952 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
10:18:08 redis.1   | 22334:C 18 Aug 2024 10:18:08.952 * Redis version=7.2.5, bits=64, commit=00000000, modified=0, pid=22334, just started
10:18:08 redis.1   | 22334:M 18 Aug 2024 10:18:08.953 * monotonic clock: POSIX clock_gettime
10:18:08 redis.1   | 22334:M 18 Aug 2024 10:18:08.953 * Running mode=standalone, port=6379.
10:18:08 redis.1   | 22334:M 18 Aug 2024 10:18:08.953 # WARNING: The TCP backlog setting of 511 cannot be enforced because kern.ipc.somaxconn is set to the lower value of 128.
10:18:08 redis.1   | 22334:M 18 Aug 2024 10:18:08.953 * Server initialized
10:18:08 redis.1   | 22334:M 18 Aug 2024 10:18:08.953 * Loading RDB produced by version 7.2.5
10:18:08 redis.1   | 22334:M 18 Aug 2024 10:18:08.953 * RDB age 7 seconds
10:18:08 redis.1   | 22334:M 18 Aug 2024 10:18:08.953 * RDB memory usage when created 1.85 Mb
10:18:08 redis.1   | 22334:M 18 Aug 2024 10:18:08.953 * Done loading RDB, keys loaded: 21, keys expired: 0.
10:18:08 redis.1   | 22334:M 18 Aug 2024 10:18:08.953 * DB loaded from disk: 0.000 seconds
10:18:08 redis.1   | 22334:M 18 Aug 2024 10:18:08.953 * Ready to accept connections tcp
10:18:09 css.1     | 
10:18:09 css.1     | Rebuilding...
10:18:09 css.1     | 
10:18:09 css.1     | Done in 322ms.
10:18:09 sidekiq.1 | undefined method `behavior=' for class ActiveSupport::Deprecation
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/wafris-2.0.0/lib/wafris.rb:15:in `<main>'
10:18:09 sidekiq.1 | <internal:/my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
10:18:09 sidekiq.1 | <internal:/my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:60:in `block (2 levels) in require'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:55:in `each'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:55:in `block in require'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:44:in `each'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:44:in `require'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler.rb:212:in `require'
10:18:09 sidekiq.1 | /my-user/Documents/GitHub/my-app/config/application.rb:25:in `<top (required)>'
10:18:09 web.1     | /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/wafris-2.0.0/lib/wafris.rb:15:in `<main>': undefined method `behavior=' for class ActiveSupport::Deprecation (NoMethodError)
10:18:09 sidekiq.1 | /my-user/Documents/GitHub/my-app/config/environment.rb:4:in `require_relative'
10:18:09 web.1     | 
10:18:09 sidekiq.1 | /my-user/Documents/GitHub/my-app/config/environment.rb:4:in `<top (required)>'
10:18:09 web.1     | ActiveSupport::Deprecation.behavior = :silence
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
10:18:09 web.1     |                           ^^^^^^^^^^^
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
10:18:09 web.1     | 	from <internal:/my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/cli.rb:305:in `boot_application'
10:18:09 web.1     | 	from <internal:/my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/cli.rb:42:in `run'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/sidekiq-7.3.1/bin/sidekiq:31:in `<top (required)>'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:60:in `block (2 levels) in require'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/bin/sidekiq:25:in `load'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:55:in `each'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/bin/sidekiq:25:in `<top (required)>'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:55:in `block in require'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:44:in `each'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:44:in `require'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler.rb:212:in `require'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:455:in `exec'
10:18:09 web.1     | 	from /my-user/Documents/GitHub/my-app/config/application.rb:25:in `<main>'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:35:in `dispatch'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/commands/server/server_command.rb:139:in `block in perform'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
10:18:09 web.1     | 	from <internal:kernel>:90:in `tap'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/cli.rb:29:in `start'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/commands/server/server_command.rb:136:in `perform'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/exe/bundle:28:in `block in <top (required)>'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bundler-2.5.17/exe/bundle:20:in `<top (required)>'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/command/base.rb:178:in `invoke_command'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/bin/bundle:25:in `load'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
10:18:09 sidekiq.1 | /my-user/.rbenv/versions/3.3.4/bin/bundle:25:in `<main>'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/command/base.rb:73:in `perform'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/command.rb:71:in `block in invoke'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/command.rb:149:in `with_argv'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/command.rb:69:in `invoke'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/commands.rb:18:in `<main>'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
10:18:09 web.1     | 	from /my-user/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
10:18:09 web.1     | 	from bin/rails:4:in `<main>'
10:18:09 sidekiq.1 | exited with code 1
10:18:09 system    | sending SIGTERM to all processes
10:18:09 web.1     | exited with code 1
10:18:09 redis.1   | 22334:signal-handler (1723947489) Received SIGTERM scheduling shutdown...
10:18:10 redis.1   | 22334:M 18 Aug 2024 10:18:10.065 * User requested shutdown...
10:18:10 redis.1   | 22334:M 18 Aug 2024 10:18:10.065 * Saving the final RDB snapshot before exiting.
10:18:10 redis.1   | 22334:M 18 Aug 2024 10:18:10.080 * DB saved on disk
10:18:10 redis.1   | 22334:M 18 Aug 2024 10:18:10.080 # Redis is now ready to exit, bye bye...
10:18:10 redis.1   | exited with code 0
10:18:10 css.1     | terminated by SIGTERM

**Comment by rmcastil** [comment]
@seanwmitchell thanks for the report. Taking a look.

**Comment by seanwmitchell** [comment]
Fixed now, thank you

**Comment by rmcastil** [comment]
@seanwmitchell thanks for the issues! I've added you to our contributor list in the README.
