### ISSUE TITLE
Error when using Passenger

### ISSUE THREAD

**Issue by aseroff** [Wafris/wafris-rb#89]
```
[Wafris] [Wafris] Detailed Error: NoMethodError - undefined method `string' for an instance of PhusionPassenger::Utils::TeeInput
Backtrace: /usr/local/rvm/gems/ruby-3.3.5/gems/wafris-2.0.3/lib/wafris/wafris_request.rb:16:in `initialize'
```
Let me know if there's any other information I can provide.

**Comment by mbuckbee** [comment]
Thanks for the report - can you please provide what version of Rack/Rails you're on as well as the version of Phusion Passenger? Appreciated.

**Comment by aseroff** [comment]
Rack 3.1.7
Rails 7.2.1
Phusion Passenger: 6.0.23

**Comment by rmcastil** [comment]
@aseroff we plan on addressing this with the next release of the gem. I'll let you know when it's available.

**Comment by rmcastil** [comment]
@aseroff this was handled in #92. Let us know if you're still having issues.

**Comment by aseroff** [comment]
@rmcastil Looks good here, thank you!
