### ISSUE TITLE
Proposal: in Rails applications, allow API key to be provided in credentials rather than an ENV variable

### ISSUE THREAD

**Issue by aseroff** [Wafris/wafris-rb#95]

**Comment by seanwmitchell** [comment]
> @seanwmitchell That wasn't enough for me. Do you have an initializer or something that tells wafris to use credentials instead of env?

Sorry, you are correct, I have it in the root of my ROR's app folder in a .env file. All this time I thought it was using my Rails Credentials but I was wrong. You're correct.

**Comment by rmcastil** [comment]
@aseroff and @seanwmitchell this has been requested by multiple people. I've got a couple other issues to address but I'll get to this some time this week.

**Comment by rmcastil** [comment]
So this was a bug created in our migration in v2. Right now the state is as follows
![image (1)](https://github.com/user-attachments/assets/af445fe9-707d-4e37-a47f-5982ee1c17c3)

A pull request is incoming to get it closer to 
![image (2)](https://github.com/user-attachments/assets/73abcb73-ed26-45ad-ba50-48412df87b08)

**Comment by rmcastil** [comment]
You can find the updates in v2.2.0. I've also updated the README with instructions. Thanks for the suggestion!

**Comment by seanwmitchell** [comment]
> @rmcastil upgraded and working, thanks for the feature, now all my credentials are back together 🤗

Worked for me too.

As per the Wafris GitHub read me file, I created a configuration/initializer/wafris.rb with

if Rails.env.production?
  Wafris.configure do |config|
    config.api_key = Rails.application.credentials.wafris_api_key
  end
end
